services:
  - type: web
    name: json-resume-online
    runtime: node
    buildCommand: bun install && bun run build
    startCommand: bun start
    envVars:
      - key: NODE_ENV
        value: production
