services:
  - type: web
    name: json-resume-online
    runtime: node
    buildCommand: bun install
    startCommand: bun run build && bun start
    envVars:
      - key: NODE_ENV
        value: production
