services:
  - type: web
    name: json-resume-online
    runtime: node
    buildCommand: NODE_ENV=development bun install && bun x vite build
    startCommand: bun start
    envVars:
      - key: NODE_ENV
        value: production
